namespace Quantira.Application.Chat.DTOs;

/// <summary>
/// Read model for a single chat message returned by
/// <c>GetChatHistoryQueryHandler</c>. Used to restore conversation
/// state in the chat UI.
/// </summary>
/// <param name="Role">
/// The sender of the message.
/// "user" for messages from the authenticated user.
/// "assistant" for responses generated by the AI model.
/// </param>
/// <param name="Content">The full text content of the message.</param>
/// <param name="CreatedAt">UTC timestamp of when the message was persisted.</param>
public sealed record ChatMessageDto(
    string Role,
    string Content,
    DateTime CreatedAt);